"""add_prompt_version_and_token_tracking

Revision ID: 83e2d64be244
Revises: 143289b4cbed
Create Date: 2026-07-07 23:31:21.943572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e2d64be244'
down_revision: Union[str, Sequence[str], None] = '143289b4cbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('prompt_version', sa.String(length=20), nullable=True))
    op.add_column('generations', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('generations', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('generations', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('generations', sa.Column('duration_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'duration_ms')
    op.drop_column('generations', 'total_tokens')
    op.drop_column('generations', 'output_tokens')
    op.drop_column('generations', 'input_tokens')
    op.drop_column('generations', 'prompt_version')
    # ### end Alembic commands ###
