"""Individual test case generated by the AI."""

from typing import Any

from pydantic import BaseModel, Field


ALLOWED_CATEGORIES = frozenset({
    "happy_path",
    "edge_case",
    "error_handling",
    "boundary",
    "negative",
    "performance",
    "type_check",
})


class TestCase(BaseModel):
    """A single test case within a test suite."""

    name: str = Field(description="Test function name (should start with test_)")
    description: str = Field(description="Human-readable test purpose")
    category: str = Field(description="Test category (happy_path, edge_case, etc.)")
    inputs: dict[str, Any] = Field(
        default_factory=dict, description="Input arguments as name-value pairs"
    )
    expected_output: Any = Field(description="Expected return value or behavior")
    assertions: list[str] = Field(
        default_factory=list,
        description="Python assertion statements",
    )
