"""TestGen AI v2.3 — Domain Models & AgentWorkflowContext

Immutable domain models and shared workflow context object establishing shared data contracts
across all agents, infrastructure services, and workflow orchestrators.
Contains zero I/O, database logic, or framework dependencies.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class GenerationRequest:
    """Incoming test generation request payload domain model."""

    source_code: str
    specification: Optional[str] = None
    language: str = "python"
    framework: str = "pytest"
    user_id: Optional[str] = None


@dataclass(frozen=True)
class RepositoryContext:
    """Workspace AST context representation (imports, types, call graph, fixtures)."""

    file_path: Optional[str] = None
    imports: List[str] = field(default_factory=list)
    custom_types: List[str] = field(default_factory=list)
    pytest_fixtures: List[str] = field(default_factory=list)
    call_graph: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class TestPlan:
    """Structured test planning blueprint generated by PlannerAgent."""

    __test__ = False

    target_functions: List[str] = field(default_factory=list)
    test_cases: List[Dict[str, Any]] = field(default_factory=list)
    mock_requirements: List[str] = field(default_factory=list)
    edge_cases: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class CandidateTest:
    """Generated candidate unit test representation."""

    test_name: str
    test_code: str
    target_function: str
    imports: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class ReviewReport:
    """Static analysis review feedback generated by ReviewerAgent."""

    is_approved: bool = True
    flaws: List[str] = field(default_factory=list)
    missing_assertions: List[str] = field(default_factory=list)
    smell_diagnostics: List[Dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class RepairAction:
    """Surgical test repair action generated by RepairAgent."""

    repair_type: str
    original_code: str
    repaired_code: str
    reason: str


@dataclass(frozen=True)
class ProviderDecision:
    """LLM provider selection decision metadata."""

    selected_provider: str
    strategy_used: str
    estimated_cost: float = 0.0
    latency_ms: float = 0.0


@dataclass(frozen=True)
class PromptPayload:
    """Rendered prompt payload with metadata."""

    template_name: str
    rendered_system: str
    rendered_user: str
    version: str = "v2.3"


@dataclass(frozen=True)
class QualityReport:
    """Consolidated quality evaluation report."""

    overall_score: float = 0.0
    rating: str = "UNKNOWN"
    line_coverage_pct: float = 0.0
    mutation_score_pct: float = 0.0
    smell_count: int = 0


@dataclass(frozen=True)
class ReasoningTrace:
    """Step-by-step cognitive agent decision entry."""

    timestamp: str
    agent_name: str
    step_action: str
    rationale_summary: str


@dataclass(frozen=True)
class TokenUsage:
    """Input/output token counters and estimated cost."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cost_usd: float = 0.0


@dataclass
class AgentWorkflowContext:
    """Shared mutable execution state container passed across all cognitive agents.

    Flows through every agent via `execute(context: AgentWorkflowContext) -> AgentWorkflowContext`.
    """

    request: GenerationRequest
    repository_context: RepositoryContext = field(default_factory=RepositoryContext)
    test_plan: Optional[TestPlan] = None
    candidate_tests: List[CandidateTest] = field(default_factory=list)
    review_report: Optional[ReviewReport] = None
    repair_history: List[RepairAction] = field(default_factory=list)
    prompt_payload: Optional[PromptPayload] = None
    provider_decision: Optional[ProviderDecision] = None
    token_usage: TokenUsage = field(default_factory=TokenUsage)
    reasoning_traces: List[ReasoningTrace] = field(default_factory=list)
    quality_report: Optional[QualityReport] = None

    def add_reasoning_trace(self, agent_name: str, step_action: str, rationale_summary: str) -> None:
        """Append an entry to the append-only reasoning trace log."""
        now = datetime.now(timezone.utc).isoformat()
        trace = ReasoningTrace(
            timestamp=now,
            agent_name=agent_name,
            step_action=step_action,
            rationale_summary=rationale_summary,
        )
        self.reasoning_traces.append(trace)

    def add_repair_action(self, repair_type: str, original_code: str, repaired_code: str, reason: str) -> None:
        """Append a repair action to the append-only repair history."""
        action = RepairAction(
            repair_type=repair_type,
            original_code=original_code,
            repaired_code=repaired_code,
            reason=reason,
        )
        self.repair_history.append(action)
